export { default as Home } from './Home'
export { default as Music } from './Music'
export { default as AboutHer } from './AboutHer'
export { default as Memories } from './Memories'
export { default as KataKata } from './KataKata'
